name: bhagawad_geeta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.3.5
  velocity_x: ^4.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_annotation: ^4.8.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
